### ISSUE TITLE
Allow for tuples to be set into item bounds

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#255] opened 2021-01-19 23:02 UTC
In https://github.com/stac-utils/stactools/pull/41, using the bounds attribute on a shapely geometry meant the bounds of an item were being set to a tuple instead of a list. This caused `Extent.from_items` to fail as it ends up using a `+` operator against a list and a tuple. We should guard against this and other cases by either converting bbox to a property and performing conversions in the property set, or changing the code using that attribute to handle the case where it is a tuple.

**Comment by pjhartzell** [comment] 2023-02-06 23:08
>This caused Extent.from_items to fail as it ends up using a + operator against a list and a tuple.

This will no longer fail given the changes in c78f832a0462f27f17b420e93af7970c5f285e2d to `Extent.from_items()` in collection.py. The underlying issue could still be addressed (ability to store a bbox on an Item as a tuple instead of a list), but there is little type enforcement elsewhere in the Item class. For example, you can set `datetime` and `geometry` to empty strings even though they are supposed to be a `datetime` and `dict`, respectively.

@gadomski Thoughts? My initial reaction is not to check/cast/enforce the type for a single attribute when: 1) it isn't done for the other attributes, and 2) the motivating problem is now moot.

**Comment by gadomski** [comment] 2023-02-07 12:53
> My initial reaction is not to check/cast/enforce the type for a single attribute when: 1) it isn't done for the other attributes, and 2) the motivating problem is now moot.

Makes sense to me.

**Comment by pjhartzell** [comment] 2023-02-07 13:49
Closing since the issue is now moot.

**Closed by pjhartzell** 2023-02-07 13:49 UTC
Labels: enhancement
