### ISSUE TITLE
Unauthorized error when validating projection extension

### ISSUE THREAD

**Issue by simonvb00** [stac-utils/pystac#1409] opened 2024-09-25 06:42 UTC
Hi all,

I recently noticed that during the validation of the projection extension (using this schema: https://stac-extensions.github.io/projection/v1.1.0/schema.json), another schema is retrieved for the proj:projjson field. However, when retrieving this schema, the following error occurs:
`Traceback (most recent call last):
  File "/home/<name>/.local/lib/python3.10/site-packages/fsspec/implementations/http.py", line 419, in _info
    await _file_info(
  File "/home/<name>/.local/lib/python3.10/site-packages/fsspec/implementations/http.py", line 832, in _file_info
    r.raise_for_status()
  File "/home/<name>/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://proj.org/schemas/v0.5/projjson.schema.json')`

However, using curl/wget locally doesn't seem to cause any issues when retrieving 'https://proj.org/schemas/v0.5/projjson.schema.json', while retrieval with the stac validator always results in an error. Could it be an issue with the HTTP client?

**Comment by simonvb00** [comment] 2024-09-25 10:04
A workaround could be to use the cache in the JsonSchemaSTACValidator object and read the schema from disk. However this is quite cumbersome and the original problem should probably be looked at.

**Comment by gadomski** [comment] 2024-09-25 11:35
Thanks for reporting! I ran into a similar issue in another repo (https://github.com/stac-utils/stac-rs/pull/440) recently and fixed it by twiddling with how TLS was handled. I wonder if something similar is going on here, I'll take a look.

There's two things contributing to the issue:

- https://proj.org/schemas/v0.5/projjson.schema.json is a redirect to https://proj.org/en/latest/schemas/v0.5/projjson.schema.json — IMO it should be considered bad practice to put a redirect into a schema, so I'll raise an issue on the proj extension to fix that
- Feels like the cloudflare that's serving that redirect is broken somehow, because I've found that some TLS configuration (e.g. on my mac) work fine, but others (e.g. on Github Actions) don't

> A workaround could be to use the cache in the JsonSchemaSTACValidator object and read the schema from disk.

We do this for some of the core schemas, but we can't know the full space of schemas that we _might_ be asked to validate so eventually we'll have to hit the network for something

**Comment by gadomski** [comment] 2024-09-25 12:07
@simonvb00 can you provide more information about your system? I was not able to reproduce on either ubuntu or macos using the following one-liner:

```shell
python -c "import pystac; pystac.read_file('https://raw.githubusercontent.com/radiantearth/stac-spec/refs/tags/v1.1.0/examples/extensions-collection/proj-example/proj-example.json').validate()"
```

**Comment by simonvb00** [comment] 2024-09-25 14:30
After some debugging, I found that the following script causes the error:
`import stactools.sentinel2.stac
import pystac
pystac.read_file('https://raw.githubusercontent.com/radiantearth/stac-spec/refs/tags/v1.1.0/examples/extensions-collection/proj-example/proj-example.json').validate()`

The reason for the error is due to the stactools.sentinel2.stac package using FsspecStacIO instead of the DefaultStacIO: ([see stactools/sentinel2/__inti__.py](https://github.com/stactools-packages/sentinel2/blob/main/src/stactools/sentinel2/__init__.py#L3)).

Should I open an issue at stactools? The issue is also present with sentinel1 stactools. The ffspec open seems to fail.

**Comment by gadomski** [comment] 2024-09-26 12:02
@simonvb00 I cannot reproduce with the following on macos or ubuntu:

```shell
python -c "import stactools.core; stactools.core.use_fsspec(); import pystac; pystac.read_file('https://raw.githubusercontent.com/radiantearth/stac-spec/refs/tags/v1.1.0/examples/extensions-collection/proj-example/proj-example.json').validate()"
```

What's your system?

> Should I open an issue at stactools?

Probably not. My _guess_ is that your problem lies somewhere down in how **fsspec** makes HTTP requests. Looks like **fsspec** uses https://docs.aiohttp.org, so my instinct is that they're doing TLS slightly different than **requests**.

**Comment by gadomski** [comment] 2024-09-26 12:17
On macos in my test environment, I'm at:

```text
pystac==1.10.1
stactools==0.5.3
aiohttp==3.10.6
fsspec==2024.9.0
```

The only difference there is **aiohttp**, so try upgrading that? Also, can you try inside a container, e.g. with https://hub.docker.com/_/python?

**Comment by simonvb00** [comment] 2024-09-26 13:11
If I run this image python:3.10-slim like this:
`docker run -it python:3.10-slim /bin/bash`
And install these packages: 
`pip install pystac[validation]==1.10.1 pystac-client==0.8.3 stactools==0.5.3`
Then this command:
`python -c "import stactools.core; stactools.core.use_fsspec(); import pystac; pystac.read_file('https://raw.githubusercontent.com/radiantearth/stac-spec/refs/tags/v1.1.0/examples/extensions-collection/proj-example/proj-example.json').validate()"`
Results in this error:
`aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://proj.org/schemas/v0.7/projjson.schema.json'
`
Normally you should be able to reproduce it now!

**Comment by gadomski** [comment] 2024-09-26 21:11
Thanks @simonvb00, I can reproduce. Unfortunately, I can't narrow down the problem any further than:

- **requests**, which is the **pystac** default, uses **urllib3** under the hood for TLS
- **aiohttp** implements its own

I think your best workaround is just to disable the **fsspec** IO — default StacIO should work fine. If you need to use the **fsspec** StacIO on objects, pass it directly, e.g.:

```python
catalog = pystac.read_file("http://pystac.test/catalog.json", stac_io=FsspecStacIO())
```

I'm going to close this issue as it's not a **pystac** issue. If you believe that the **sentinel2** package shouldn't use the **fsspec** IO, please open an issue over there. Thanks for your iterations on this one! 🍻

**Closed by gadomski** 2024-09-26 21:11 UTC

**Comment by simonvb00** [comment] 2024-09-30 14:12
Hi @gadomski! I changed the IO component back to the default one and this seems to work fine! Thanks for all the help! 🍻
