### ISSUE TITLE
Sentinel Hub API throws KeyError on 'links' when running validate_all

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pystac#344] opened 2021-05-17 17:13 UTC
The code below results in this exception (KeyError on 'links'). This API does require authentication for some endpoints, so it's possible the 4xx responses are still trying to be parsed as a Catalog. 

```
import pystac_client

pystac_client.Client.open("https://services.sentinel-hub.com/api/v1/catalog/").validate_all()
```

Exception:

```
Traceback (most recent call last):
  File "/Users/philvarner/code/stac-api-validation-suite/stac_api_validation_suite/validate_all_error.py", line 19, in <module>
    pystac_client.Client.open("https://services.sentinel-hub.com/api/v1/catalog/").validate_all()
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/catalog.py", line 678, in validate_all
    for child in self.get_children():
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/stac_object.py", line 343, in get_stac_objects
    link.resolve_stac_object(root=self.get_root())
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/link.py", line 146, in resolve_stac_object
    obj = STAC_IO.read_stac_object(target_href, root=root)
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/stac_io.py", line 131, in read_stac_object
    return cls.stac_object_from_dict(d, href=uri, root=root)
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/serialization/__init__.py", line 37, in stac_object_from_dict
    return Catalog.from_dict(d, href=href, root=root)
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/catalog.py", line 786, in from_dict
    catalog_type = CatalogType.determine_type(d)
  File "/Users/philvarner/.local/share/virtualenvs/stac-api-validation-suite-tzI1nfla/lib/python3.9/site-packages/pystac/catalog.py", line 60, in determine_type
    for link in stac_json['links']:
KeyError: 'links'
```

**Comment by duckontheweb** [comment] 2021-05-25 01:10
Oddly enough, I get a different error when I run that code on either PySTAC 0.5.6 or 1.0.0-beta.2:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jduckworth/Code/pystac/pystac/catalog.py", line 768, in validate_all
    for child in self.get_children():
  File "/Users/jduckworth/Code/pystac/pystac/stac_object.py", line 284, in get_stac_objects
    link.resolve_stac_object(root=self.get_root())
  File "/Users/jduckworth/Code/pystac/pystac/link.py", line 204, in resolve_stac_object
    obj = stac_io.read_stac_object(target_href, root=root)
  File "/Users/jduckworth/Code/pystac/pystac/stac_io.py", line 137, in read_stac_object
    d = self.read_json(source)
  File "/Users/jduckworth/Code/pystac/pystac/stac_io.py", line 116, in read_json
    txt = self.read_text(source)
  File "/Users/jduckworth/Code/pystac/pystac/stac_io.py", line 179, in read_text
    return self.read_text_from_href(href, *args, **kwargs)
  File "/Users/jduckworth/Code/pystac/pystac/stac_io.py", line 188, in read_text_from_href
    raise Exception("Could not read uri {}".format(href)) from e
Exception: Could not read uri https://services.sentinel-hub.com/api/v1/catalog/collections/sentinel-2-l1c
```

@philvarner Could you verify which version of PySTAC you're running?

Judging from the traceback in the original issue, I would say that this has the same root cause as #340. That API returns a JSON response like this for `401` errors, and PySTAC is falling back to assuming it's a Catalog:

```json
{
    "code": 401,
    "description": "You are not authorized - please provide header [Authorization: Bearer <accessToken>] with your request."
}
```

**Comment by gadomski** [comment] 2022-11-08 23:05
This issue now appears to be caught at the **pystac-client** level:

```shell
➜  pystac git:(main) ✗ cat > issues-344.py
import pystac_client

pystac_client.Client.open(
    "https://services.sentinel-hub.com/api/v1/catalog/"
).validate_all()
```

```shell
➜  pystac git:(main) ✗ python issues-344.py 
Traceback (most recent call last):
  File "/Users/gadomski/Code/pystac/issues-344.py", line 5, in <module>
    ).validate_all()
  File "/Users/gadomski/Code/pystac/pystac/catalog.py", line 875, in validate_all
    for child in self.get_children():
  File "/Users/gadomski/Code/pystac/pystac/stac_object.py", line 317, in get_stac_objects
    link.resolve_stac_object(root=self.get_root())
  File "/Users/gadomski/Code/pystac/pystac/link.py", line 318, in resolve_stac_object
    obj = stac_io.read_stac_object(target_href, root=root)
  File "/Users/gadomski/Code/pystac/pystac/stac_io.py", line 231, in read_stac_object
    d = self.read_json(source, *args, **kwargs)
  File "/Users/gadomski/Code/pystac/pystac/stac_io.py", line 202, in read_json
    txt = self.read_text(source, *args, **kwargs)
  File "/Users/gadomski/.pyenv/versions/pystac/lib/python3.10/site-packages/pystac_client/stac_api_io.py", line 97, in read_text
    return self.request(href, *args, **kwargs)
  File "/Users/gadomski/.pyenv/versions/pystac/lib/python3.10/site-packages/pystac_client/stac_api_io.py", line 144, in request
    raise APIError.from_response(resp)
pystac_client.exceptions.APIError: {"code":401,"description":"You are not authorized - please provide header [Authorization: Bearer <accessToken>] with your request."}
```

Closing as not planned, please re-open if it still is a PySTAC issue (or re-open on pystac-client if there's an issue over there, but it looks ok to me).

**Closed** 2022-11-08 23:05 UTC
